Repository YehoGuy/ShoppingSystem, pull requests merged in 2025-06, with the labels that each got.

#505 init file
  Project/pom.xml
  Project/src/main/java/com/example/app/DBLayer/User/UserRepositoryDBImpl.java
  Project/src/main/java/com/example/app/InfrastructureLayer/UserRepository.java
  Project/src/main/resources/application-db-test.properties
  Project/src/main/resources/import.sql
Labels: enhancement

#519 512 finishing admin
  Frontend/src/main/java/UI/AdminView.java
  Frontend/src/main/java/UI/AuctionListView.java
  Frontend/src/main/java/UI/BidsListView.java
  Frontend/src/main/java/UI/EditShopView.java
  Frontend/src/main/java/UI/RegistrationView.java
  Frontend/src/main/java/UI/ShopView.java
  Project/src/main/java/com/example/app/ApplicationLayer/Shop/ShopService.java
  Project/src/main/java/com/example/app/ApplicationLayer/User/UserService.java
Labels: bug, enhancement

#513 510 make sure you see founder role on profile page
  Frontend/src/main/java/UI/MessageView.java
  Frontend/src/main/java/UI/PersonProfileView.java
  Project/src/main/java/com/example/app/ApplicationLayer/Shop/ShopService.java
  Project/src/main/java/com/example/app/ApplicationLayer/User/UserService.java
Labels: Fixes

#522 521 safe fall in case of problems with init
  Project/src/main/java/com/example/app/Config/DatabaseInitializer.java
  Project/src/main/resources/import.sql
Labels: enhancement

#528 526 fix db problems
  Frontend/src/main/bundles/prod.bundle
  Frontend/src/main/java/UI/AuctionListView.java
  Frontend/src/main/java/UI/BidsListView.java
  Frontend/src/main/java/UI/MyShopsView.java
  Project/src/main/java/com/example/app/ApplicationLayer/Item/ItemService.java
  Project/src/main/java/com/example/app/ApplicationLayer/Purchase/PurchaseService.java
  Project/src/main/java/com/example/app/ApplicationLayer/Shop/ShopService.java
  Project/src/main/java/com/example/app/DBLayer/Item/ItemRepositoryDBImpl.java
  Project/src/main/java/com/example/app/DBLayer/Message/MessageRepositoryDBImpl.java
  Project/src/main/java/com/example/app/DBLayer/Purchase/PurchaseRepositoryDBImpl.java
  Project/src/main/java/com/example/app/DBLayer/Shop/ShopRepositoryDBImpl.java
  Project/src/main/java/com/example/app/DBLayer/User/UserRepositoryDBImpl.java
  Project/src/main/java/com/example/app/DomainLayer/Item/Item.java
  Project/src/main/java/com/example/app/DomainLayer/Purchase/IPurchaseRepository.java
  Project/src/main/java/com/example/app/DomainLayer/Purchase/Reciept.java
  Project/src/main/java/com/example/app/InfrastructureLayer/PurchaseRepository.java
  Project/src/test/java/ApplicationLayerTests/PurchaseServiceTests.java
  Project/src/test/java/ApplicationLayerTests/Shop/ShopServiceAcceptanceTests.java
  Project/src/test/java/DBLayerTests/PurchaseRepositoryDBImplTests.java
Labels: bug

#539 538 fix notifications
  Project/src/main/java/com/example/app/ApplicationLayer/User/UserService.java
  Project/src/main/java/com/example/app/DBLayer/User/UserRepositoryDBImpl.java
Labels: enhancement

#542 fixed
  Project/src/main/java/com/example/app/ApplicationLayer/Purchase/PurchaseService.java
  Project/src/main/java/com/example/app/PresentationLayer/Controller/PurchaseController.java
  Project/src/test/java/PresentationLayerTests/PurchaseControllerTests.java
Labels: bug, enhancement
